name: HaskShop
version: 1.1.0
main: com.hask.shop.HaskShop
depend: [Vault]
softdepend: [Citizens]

commands:
  hs:
    description: Gerencia lojas em placas e NPCs
    usage: /hs <add|edit|remove|info|list|npcshop|reload>
    permission: shopsign.admin

permissions:
  shopsign.admin:
    description: Permite criar e gerenciar lojas
    default: op
  shopsign.use:
    description: Permite usar lojas
    default: true
